return {
	{ Id = "Poop", Name = "Poop", Chance = 2, Rarity = "Common", Value = 80, Event = false },
	{ Id = "ToiletPaper", Name = "Toilet Paper", Chance = 8, Rarity = "Uncommon", Value = 280, Event = false },
	{ Id = "Rat", Name = "Rat", Chance = 25, Rarity = "Rare", Value = 1000, Event = false },
	{ Id = "Fish", Name = "Fish", Chance = 80, Rarity = "Rare", Value = 2480, Event = false },
	{ Id = "Duck", Name = "Duck", Chance = 250, Rarity = "Epic", Value = 8000, Event = false },
	{ Id = "GoldenPoop", Name = "Golden Poop", Chance = 1000, Rarity = "Legendary", Value = 30000, Event = false },
	{ Id = "ToiletBaby", Name = "Toilet Baby", Chance = 5000, Rarity = "Mythic", Value = 150000, Event = false },
	{ Id = "SewerShark", Name = "Sewer Shark", Chance = 25000, Rarity = "Godly", Value = 800000, Event = false },
	{ Id = "KingPoop", Name = "King Poop", Chance = 100000, Rarity = "Mythic", Value = 5000000, Event = true },
	{ Id = "AlienToilet", Name = "Alien Toilet", Chance = 1000000, Rarity = "Secret", Value = 40000000, Event = true },
	{ Id = "Mystery", Name = "???", Chance = 10000000, Rarity = "Secret", Value = 500000000, Event = true },
}
