return {
	{ Id = "Poop", Name = "Poop", Chance = 2, Rarity = "Common", Value = 2, Event = false },
	{ Id = "ToiletPaper", Name = "Toilet Paper", Chance = 8, Rarity = "Uncommon", Value = 7, Event = false },
	{ Id = "Rat", Name = "Rat", Chance = 25, Rarity = "Rare", Value = 25, Event = false },
	{ Id = "Fish", Name = "Fish", Chance = 80, Rarity = "Rare", Value = 62, Event = false },
	{ Id = "Duck", Name = "Duck", Chance = 250, Rarity = "Epic", Value = 200, Event = false },
	{ Id = "GoldenPoop", Name = "Golden Poop", Chance = 1000, Rarity = "Legendary", Value = 750, Event = false },
	{ Id = "ToiletBaby", Name = "Toilet Baby", Chance = 5000, Rarity = "Mythic", Value = 3750, Event = false },
	{ Id = "SewerShark", Name = "Sewer Shark", Chance = 25000, Rarity = "Godly", Value = 20000, Event = false },
	{ Id = "KingPoop", Name = "King Poop", Chance = 100000, Rarity = "Mythic", Value = 125000, Event = true },
	{ Id = "AlienToilet", Name = "Alien Toilet", Chance = 1000000, Rarity = "Secret", Value = 1000000, Event = true },
	{ Id = "Mystery", Name = "???", Chance = 10000000, Rarity = "Secret", Value = 12500000, Event = true },
}
