return {
	Common = { Order = 1, Color = Color3.fromRGB(160, 160, 160) },
	Uncommon = { Order = 2, Color = Color3.fromRGB(60, 220, 80) },
	Rare = { Order = 3, Color = Color3.fromRGB(50, 140, 255) },
	Epic = { Order = 4, Color = Color3.fromRGB(160, 70, 240) },
	Legendary = { Order = 5, Color = Color3.fromRGB(255, 180, 30) },
	Mythic = { Order = 6, Color = Color3.fromRGB(255, 50, 200) },
	Godly = { Order = 7, Color = Color3.fromRGB(240, 50, 50) },
	Celestial = { Order = 8, Color = Color3.fromRGB(160, 240, 255) },
	Secret = { Order = 9, Color = Color3.fromRGB(20, 20, 20) },
}
