"""Wave 1 group B: twelve original static toy collectibles, author Z-up/-Y front.

All color, UV, geometry finishing and eye conventions come from read-only lib.py.
No existing assets or palette files are regenerated by these builders.
"""
import math
import bpy
from lib import sphere, box, cylinder, torus, tube, lathe, prism, mesh, eyes, smile, star, finish


def puff(name, loc, scale, color, detail=10, rings=6, smooth=True):
    return sphere(name, loc, scale, color, detail, rings, smooth)


def small(name, loc, scale, color):
    return puff(name, loc, scale, color, 8, 4)


def softbox(name, loc, size, color, bevel=.04):
    """Single bevel segment for small trim; retain the shared palette mapping."""
    bpy.ops.mesh.primitive_cube_add(size=1,location=loc)
    obj=bpy.context.object
    obj.name=name
    obj.scale=size
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    mod=obj.modifiers.new('Small molded edge','BEVEL')
    mod.width=min(bevel,min(size)*.45)
    mod.segments=1
    return finish(obj,color,False)


def line(name, points, radius, color, sides=6):
    return tube(name, points, [radius]*len(points), color, sides)


def bow(loc, color="pink", scale=1):
    x,y,z=loc
    for s in (-1,1):
        prism("Bow wing",[(x+s*.06*scale,z),(x+s*.34*scale,z+.17*scale),
                         (x+s*.34*scale,z-.17*scale)],.16*scale,color,y)
    small("Bow knot",loc,(.12*scale,.12*scale,.12*scale),color)


def plunger_pogo():
    lathe("Bell suction foot",[(.10,.02),(.67,.02),(.68,.13),(.56,.24),(.40,.48),(.17,.56),(.10,.49)],(0,0,0),"red",segments=16)
    torus("Rolled rubber edge",(0,0,.11),.61,.08,"red",segments=16,sides=4)
    line("Leaning wooden shaft",[(0,0,.40),(.21,0,2.35)],.105,"wood",10)
    puff("Rounded spring sleeve",(.07,0,.99),(.29,.27,.53),"purple",12,8)
    for z in (.77,1.02,1.26):
        torus("Molded sleeve rib",(.07,0,z),.265,.048,"purple",segments=12,sides=4)
    for s in (-1,1):
        line("Cyan handlebar arm",[(.14,0,1.48),(.14+s*.64,0,1.48),(.14+s*.80,-.06,1.73)],.10,"cyan",8)
        puff("Handlebar grip",(.14+s*.79,-.06,1.75),(.15,.16,.24),"cyan",8,6)
    eyes(.28,-.20,1.98,.285,x=.18)
    puff("Orange crash helmet",(.18,.03,2.39),(.67,.47,.40),"orange",12,8)
    box("Helmet peak",(.18,-.41,2.31),(1.15,.32,.13),"orange",.05)
    line("Helmet grin",[(-.03,-.575,2.31),(.15,-.59,2.27),(.34,-.575,2.31)],.024,"ink")
    box("Helmet stripe",(.18,-.025,2.775),(.16,.39,.035),"white",0)


def bath_mat_bat():
    # Broad scallops carry the towel/bat silhouette, with actual thick hems.
    for s in (-1,1):
        outline=[(.38,1.12),(.88,1.67),(1.55,1.57),(1.40,.60),(1.10,.81),(.91,.40),(.65,.67),(.43,.42)]
        prism("Scalloped towel wing",[(s*x,z) for x,z in outline],.24,"purple",.06)
        panel=[(.55,1.12),(.92,1.48),(1.38,1.43),(1.28,.82),(1.06,.99),(.90,.64),(.70,.85)]
        prism("Pink underside panel",[(s*x,z) for x,z in panel],.035,"pink",-.08)
        line("Cream scalloped hem",[(s*x,-.085,z) for x,z in outline[2:]],.035,"cream")
    body=box("Folded rectangular bath mat",(0,0,.79),(.98,.48,1.28),"purple",.16)
    body.rotation_euler.y=-.05
    prism("Folded top corners",[(-.49,1.28),(-.40,1.74),(-.08,1.46),(.20,1.46),(.46,1.69),(.49,1.20)],.27,"purple",.03)
    line("Bottom mat hem",[(-.40,-.26,.24),(0,-.28,.18),(.40,-.26,.24)],.04,"cream")
    eyes(.235,-.27,1.05,.22)
    puff("Small bat mouth",(0,-.29,.63),(.23,.06,.11),"ink")
    for s in (-1,1):
        prism("Felt fang",[(s*.14-.05,.68),(s*.14+.05,.68),(s*.14,.50)],.07,"cream",-.36)
    nose=box("Orange clothespin nose",(0,-.41,.80),(.15,.25,.25),"orange",.04)
    nose.rotation_euler.y=-.15
    box("Clothespin split",(0,-.548,.75),(.025,.014,.11),"ink",0)


def disco_bidet():
    for s in (-1,1):
        shoe=box("Blue platform shoe",(s*.47,-.12,.18),(.65,.87,.36),"blue",.13)
        shoe.rotation_euler.z=s*-.16
        box("Platform sole",(s*.47,-.12,.045),(.64,.86,.09),"purple",.025)
    lathe("Mini bidet bowl",[(.10,.39),(.41,.43),(.70,.66),(.84,1.02),(.81,1.12),(.65,1.12),(.51,.79),(.10,.68)],(0,-.12,0),"white",scale=(1,.90,1),segments=16)
    torus("White seat lip",(0,-.12,1.08),.73,.09,"white",scale=(1,.90,1),segments=16,sides=6)
    box("Checker tank",(0,.31,1.40),(1.32,.57,1.23),"white",.13)
    for row in range(2):
        for col in range(3):
            softbox("Large disco checker",(-.43+col*.43,.002,1.17+row*.49),(.39,.055,.44),"cyan" if (row+col)%2 else "purple",.035)
    box("Pink visor",(0,-.08,1.91),(1.23,.31,.56),"pink",.16)
    eyes(.29,-.27,1.93,.195)
    line("Microphone nozzle stem",[(-.65,.10,1.26),(-.96,-.37,1.25),(-.97,-.41,1.50)],.095,"gray",8)
    puff("Microphone nozzle head",(-.97,-.41,1.55),(.17,.16,.24),"gray")
    torus("Microphone grille band",(-.97,-.41,1.57),.165,.018,"ink",scale=(1,.94,1),segments=12,sides=4)
    line("Raised glove arm",[(.62,.20,1.28),(.98,.18,1.51),(1.01,.14,1.98)],.105,"gold",8)
    puff("Disco mitten",(1.01,.12,2.08),(.21,.15,.25),"gold")
    small("Glove thumb",(.83,-.005,2.02),(.12,.11,.13),"gold")
    star("Static cyan sparkle",(-.71,.06,2.27),.17,"cyan")


def towel_band(radius, z, phase):
    # A broad helical ribbon with rounded rectangular cross section, not a hose.
    verts=[]
    steps=18
    section=[(-.075,-.19),(.075,-.19),(.11,-.13),(.11,.13),(.075,.19),(-.075,.19),(-.11,.13),(-.11,-.13)]
    for i in range(steps+1):
        t=i/steps
        a=phase+t*math.tau*1.08
        r=radius+.13*t
        for dr,dz in section:
            verts.append(((r+dr)*math.cos(a),(r+dr)*math.sin(a),z+t*.59+dz))
    faces=[tuple(reversed(range(8))),tuple(steps*8+j for j in range(8))]
    for i in range(steps):
        for j in range(8):
            k=i*8+j
            faces.append((k,i*8+(j+1)%8,(i+1)*8+(j+1)%8,k+8))
    mesh("Thick folded spiral towel band",verts,faces,"mint",True)
    pts=[]
    for i in range(steps+1):
        t=i/steps
        a=phase+t*math.tau*1.08
        r=radius+.13*t+.09
        pts.append((r*math.cos(a),r*math.sin(a),z+t*.59-.15))
    line("Cream towel hem",pts,.03,"cream",4)


def towel_tornado():
    puff("Orange bath slipper sole",(0,-.17,.15),(.56,.68,.15),"orange",12,6)
    puff("Orange slipper toe",(0,-.42,.26),(.51,.37,.26),"orange")
    for r,z,p in [(.24,.46,.8),(.47,1.00,1.7),(.70,1.54,2.7)]:
        towel_band(r,z,p)
    puff("Upper towel fold",(0,.02,1.91),(.73,.65,.34),"mint",12,6)
    prism("Pink towel flag",[(.57,2.02),(1.12,2.27),(.99,1.72),(.65,1.65)],.16,"pink",.16)
    line("Flag hem",[(1.12,.06,2.27),(.99,.06,1.72),(.65,.06,1.65)],.035,"cream")
    eyes(.28,-.86,1.96,.24)
    mouth=puff("Dizzy offset mouth",(.08,-.88,1.63),(.13,.052,.055),"ink",8,4)
    mouth.rotation_euler.y=.18


def porcelain_poodle():
    puff("Porcelain teapot chest",(-.03,.10,.98),(.79,.42,.63),"white",12,8)
    for x in (-.52,.53):
        for y in (-.28,.30):
            cylinder("Thick porcelain leg",(x,y,.44),.14,.65,"white",8)
            cylinder("Gold paw cuff",(x,y,.25),.20,.16,"gold",10)
            puff("White paw",(x,y-.08,.12),(.23,.22,.13),"white",8,4)
    # Three signature fur puffs: two floppy ears and the large topknot.
    puff("Poodle head",(-.44,-.06,1.62),(.47,.39,.47),"white",12,6)
    for x,y,z,sc in [(-.88,.04,1.58,(.24,.29,.40)),(-.08,.10,1.58,(.23,.29,.40)),(-.47,.01,2.04,(.40,.35,.29))]:
        puff("Spherical porcelain fur puff",(x,y,z),sc,"white")
    for s in (-1,1):
        puff("Gray eye edging",(-.46+s*.195,-.409,1.75),(.205,.065,.235),"gray",8,6)
    eyes(.195,-.452,1.75,.175,x=-.46)
    tube("Cream faucet spout snout",[(-.45,-.35,1.47),(-.45,-.59,1.49),(-.49,-.77,1.42),(-.54,-.81,1.30)],[.18,.18,.16,.14],"cream",10)
    torus("Spout rolled lip",(-.54,-.81,1.30),.13,.04,"cream",segments=12,sides=4)
    small("Recessed spout opening",(-.54,-.81,1.275),(.095,.095,.018),"ink")
    line("Prim smile",[(-.60,-.885,1.46),(-.49,-.935,1.40),(-.38,-.875,1.46)],.023,"ink")
    line("Gold curled tail",[(.53,.20,1.06),(.98,.22,1.34),(1.10,.22,1.76),(.91,.20,1.95),(.72,.18,1.79),(.83,.17,1.65)],.10,"gold",8)
    bow((-.48,-.51,1.19),scale=.70)


def faucet_pharaoh():
    cylinder("Broad golden pedestal",(0,.05,.16),.74,.32,"gold",16)
    # Open arch remains empty below the face and beard.
    line("Inverted U faucet",[(-.51,0,.27),(-.54,0,1.38),(-.42,0,1.95),(0,0,2.15),(.45,0,1.96),(.56,0,1.53)],.23,"gold",12)
    outline=[(-.70,1.38),(-.94,2.05),(-.71,2.64),(0,2.89),(.71,2.64),(.94,2.05),(.70,1.38)]
    prism("Blue fan headdress",outline,.27,"blue",.18)
    for s in (-1,1):
        for i in range(3):
            z=1.61+i*.32
            box("Gold headdress stripe",(s*(.75+.035*(i==1)),.023,z),(.32,.055,.105),"gold",.025)
    prism("Gold fan center stripe",[(-.10,2.13),(-.14,2.78),(0,2.83),(.14,2.78),(.10,2.13)],.06,"gold",.01)
    puff("Faucet face bridge",(0,-.09,1.97),(.54,.26,.41),"gold",12,6)
    eyes(.24,-.32,2.02,.21)
    smile((0,-.364,1.76),.19)
    # A solid sculpted drop, connected to the spout rather than a particle.
    tube("Cyan water drop beard",[(0,-.07,1.68),(0,-.08,1.40),(0,-.08,1.20),(0,-.08,1.10)],[.08,.20,.14,.025],"cyan",10)
    for s in (-1,1):
        arm=[(-.49,0,1.07),(-.98,0,1.15)] if s<0 else [(.56,0,1.58),(.82,0,1.27),(.98,0,1.20)]
        line("Cross handle arm",arm,.115,"gold",8)
        box("Horizontal tap cross",(s*1.02,0,1.20),(.48,.23,.15),"gold",.05)
        box("Vertical tap cross",(s*1.02,0,1.20),(.15,.23,.50),"gold",.05)
        small("Blue tap inset",(s*1.02,-.13,1.20),(.09,.035,.09),"blue")


def royal_flush_frog():
    torus("Open golden oval seat",(0,.08,.66),.97,.13,"gold",scale=(1.24,.90,1),segments=24,sides=6)
    puff("Green pear body",(0,.04,.85),(.58,.54,.71),"green",12,8)
    puff("Frog forehead beneath crown",(0,-.03,1.58),(.46,.38,.26),"green")
    puff("Cream belly",(0,-.445,.77),(.40,.095,.45),"cream")
    for s in (-1,1):
        puff("Puffed frog cheek",(s*.43,-.20,1.30),(.31,.33,.25),"green")
        puff("Seated frog haunch",(s*.45,-.20,.34),(.35,.40,.33),"green")
        # Extruded web outlines are rotated into the ground plane.
        foot=prism("Wide webbed foot",[(0,0),(.49,-.06),(.64,.18),(.47,.24),(.61,.43),(.36,.42),(.26,.57),(.06,.38)],.16,"green")
        foot.rotation_euler.x=math.pi/2
        foot.scale.x=s
        foot.location=(s*.24,-.39,.10)
        line("Front frog arm on seat",[(s*.44,-.09,.97),(s*.92,-.41,.72)],.10,"green",8)
    eyes(.30,-.39,1.56,.26)
    smile((0,-.573,1.23),.26)
    crown_outline=[(-.52,1.76),(-.57,2.17),(-.27,1.97),(0,2.29),(.27,1.97),(.57,2.17),(.52,1.76)]
    prism("Broad three point crown",crown_outline,.30,"goldLight",.015)
    for x,z in [(-.57,2.17),(0,2.29),(.57,2.17)]:
        small("Pink crown tip",(x,.015,z),(.10,)*3,"pink")


def golden_gargler():
    for s in (-1,1):
        puff("Cream singing shoe",(s*.34,-.13,.13),(.27,.38,.13),"cream",8,6)
    lathe("Hollow tapered rinsing cup",[(.38,.24),(.54,.24),(.73,1.77),(.59,1.77),(.43,.43),(.38,.43)],(0,0,0),"gold",segments=20)
    torus("Broad light gold rim",(0,0,1.75),.68,.105,"goldLight",segments=20,sides=6)
    eyes(.28,-.78,1.91,.24)
    puff("Open opera mouth",(0,-.695,1.20),(.235,.09,.31),"ink",12,8)
    small("Mouth lower glint",(0,-.788,1.03),(.13,.025,.052),"cream")
    bow((0,-.555,.69),"purple",.8)
    for s in (-1,1):
        line("Blue mitten arm",[(s*.58,0,1.11),(s*.87,-.03,1.18),(s*1.02,-.08,1.52)],.11,"blue",8)
        puff("Blue mitten",(s*1.02,-.08,1.55),(.20,.15,.25),"blue",8,6)
        small("Mitten thumb",(s*.85,-.18,1.52),(.10,.10,.13),"blue")
    for x,y,z,r in [(.73,.03,2.06,.18),(.54,.04,2.48,.14),(.15,.04,2.76,.105)]:
        puff("Cyan gargle bubble",(x,y,z),(r,)*3,"cyan",8,5)
        small("Bubble shine",(x-r*.27,y-r*.90,z+r*.30),(r*.24,r*.09,r*.24),"white")


def clogtopus():
    puff("Magenta dome head",(0,0,1.20),(.69,.60,.75),"magenta",12,8)
    for i in range(8):
        a=-math.pi/2+(i+.5)*math.tau/8
        c,s=math.cos(a),math.sin(a)
        # Eight distinct radial curls, short six-sided sections per the brief.
        pts=[(.44*c,.41*s,.81),(.85*c,.80*s,.40),(1.19*c,1.10*s,.23),(1.36*c,1.24*s,.41)]
        if i in (3,4):
            side=1 if i==3 else -1
            pts[-2]=(side*.97,.89,.40)
            pts[-1]=(side*1.35,.70,.95)
        tube("Tentacle %02d"%(i+1),pts,[.20,.17,.13,.10],"purple",6)
        tip=pts[-1]
        lathe("Red suction bell %02d"%(i+1),[(.07,0),(.23,0),(.25,.07),(.16,.19),(.08,.24)],(tip[0],tip[1],tip[2]-.04),"red",segments=8)
    eyes(.27,-.56,1.32,.24)
    line("Raised worried brow",[(-.49,-.54,1.69),(-.33,-.59,1.77),(-.15,-.58,1.72)],.043,"ink")
    puff("Tiny worried mouth",(.06,-.619,.99),(.115,.046,.075),"ink",8,4)
    puff("Cream plumber cap",(0,.04,1.91),(.60,.49,.25),"cream",12,6)
    box("Cap visor",(0,-.43,1.85),(.93,.34,.12),"cream",.05)
    # Oversized open jaw remains readable next to the front-right tentacle.
    prism("Gold open jaw wrench",[(.56,.38),(.72,.35),(.96,.96),(1.18,1.06),(1.25,1.32),(1.11,1.28),(1.03,1.09),(.86,1.16),(.90,1.37),(.75,1.45),(.66,1.19),(.78,.99)],.15,"gold",-.98)


def laundry_yeti():
    prism("Trapezoid towel body",[(-.63,.50),(.63,.50),(.91,1.91),(.69,2.30),(-.69,2.30),(-.91,1.91)],.93,"white",.05)
    for s in (-1,1):
        box("Purple slipper",(s*.43,-.13,.16),(.66,.86,.32),"purple",.14)
        # Exactly six broad towel tufts, not individual fur strands.
        for x,y,z,sz in [(s*.69,.03,1.81,(.42,.51,.43)),(s*.44,.02,2.19,(.42,.44,.36)),(s*.56,-.31,1.06,(.34,.28,.38))]:
            puff("Large folded towel tuft",(x,y,z),sz,"white",8,6)
        puff("Huge peach mitten",(s*1.02,-.10,1.14),(.32,.31,.44),"peach",10,6)
        small("Peach mitten thumb",(s*.79,-.37,1.24),(.16,.15,.23),"peach")
    puff("Cyan face panel",(0,-.48,1.83),(.62,.12,.48),"cyan",12,6)
    eyes(.255,-.58,1.96,.225)
    puff("Worried open mouth",(0,-.61,1.55),(.16,.055,.18),"ink",8,6)
    # Two rails and five struts create four real broad openings at the front.
    for z in (.50,.90):
        softbox("Basket belt rail",(0,-.45,z),(1.52,.16,.11),"gray",.025)
    for x in (-.71,-.355,0,.355,.71):
        softbox("Basket belt strut",(x,-.46,.70),(.10,.15,.42),"gray",.025)
    for s in (-1,1):
        box("Basket belt side",(s*.71,.03,.70),(.12,.98,.46),"gray",.03)
    prism("Lone pink sock",[(.08,2.33),(.11,2.76),(.43,2.76),(.41,2.49),(.67,2.46),(.66,2.25),(.29,2.25)],.21,"pink",-.40)
    box("Sock cuff",(.27,-.40,2.73),(.36,.27,.13),"pink",.035)


def steam_genie():
    cylinder("Teal tap base",(-.30,.04,.12),.47,.24,"teal",12)
    line("Teal bath tap",[(-.30,.04,.21),(-.30,.04,.61),(.02,.02,.66),(.17,-.02,.52)],.15,"teal",10)
    box("Tap cross handle",(-.31,.02,.71),(.62,.19,.12),"teal",.045)
    tube("Single S steam curl",[(.16,-.02,.52),(.44,.02,.74),(.35,.04,1.01),(-.03,.03,1.16),(-.26,.02,1.44),(0,.02,1.62)],[.105,.16,.23,.24,.29,.40],"white",10)
    puff("Violet upper body",(0,.04,1.92),(.57,.43,.61),"violet",12,8)
    for s in (-1,1):
        tube("Joined upswept sleeve",[(s*.40,.10,2.10),(s*.87,.12,1.93),(s*1.13,.07,2.22)],[.25,.27,.20],"violet",8)
        torus("Gold sleeve cuff",(s*1.13,.07,2.27),.20,.065,"gold",segments=12,sides=4)
        small("Violet mitten",(s*1.13,.07,2.41),(.18,.17,.23),"violet")
    eyes(.235,-.381,2.15,.21)
    smile((0,-.422,1.81),.29)
    for s in (-1,1):
        line("Curled pink eyebrow",[(s*.09,-.40,2.41),(s*.28,-.42,2.49),(s*.41,-.38,2.45),(s*.43,-.34,2.36)],.039,"pink")
    puff("Cream towel turban",(0,.08,2.67),(.63,.45,.30),"cream",12,6)
    seam=[]
    for i in range(13):
        x=-.50+i/12
        z=2.53+.27*(abs(x)/.50)**1.4
        y=.08-.45*math.sqrt(max(.01,1-(x/.63)**2-((z-2.67)/.30)**2))-.015
        seam.append((x,y,z))
    line("Turban wrapped seam",seam,.045,"white",6)
    small("Turban knot",(0,-.38,2.69),(.16,.13,.16),"gold")


def bath_bomb_behemoth():
    puff("Heavy faceted bath bomb",(0,.04,1.29),(.99,.88,1.05),"magenta",14,9,False)
    for x in (-.60,.60):
        for y in (-.44,.48):
            puff("Mint stone foot",(x,y,.30),(.38,.42,.34),"mint",8,5,False)
    for s in (-1,1):
        prism("Violet shoulder fin",[(s*.76,1.88),(s*1.24,1.80),(s*1.16,1.20),(s*.80,1.38)],.47,"violet",.02)
    for x,y,z,r in [(-.58,0,2.25,.27),(-.29,.03,2.43,.30),(0,.01,2.53,.33),(.33,.03,2.41,.30),(.59,0,2.23,.27)]:
        puff("Cream fizz crown lobe",(x,y,z),(r,r*.85,r),"cream",10,6)
    eyes(.17,-.829,1.48,.12)
    smile((.01,-.851,1.23),.085)
    # Open scoop cup points toward the viewer, distinct from the feet.
    line("Gold bath scoop handle",[(.95,-.20,1.58),(.93,-.64,1.29),(.84,-.94,1.02)],.075,"gold",8)
    scoop=lathe("Hollow gold scoop",[(.06,-.14),(.22,-.12),(.29,.06),(.28,.13),(.21,.13),(.15,-.04),(.06,-.05)],(0,0,0),"gold",segments=12)
    scoop.rotation_euler.x=math.pi/2
    scoop.location=(.84,-.98,.94)
    bottom=cylinder("Solid scoop bowl bottom",(.84,-.915,.94),.075,.05,"gold",12)
    bottom.rotation_euler.x=math.pi/2


BUILDERS={
    "PlungerPogo":plunger_pogo, "BathMatBat":bath_mat_bat,
    "DiscoBidet":disco_bidet, "TowelTornado":towel_tornado,
    "PorcelainPoodle":porcelain_poodle, "FaucetPharaoh":faucet_pharaoh,
    "RoyalFlushFrog":royal_flush_frog, "GoldenGargler":golden_gargler,
    "Clogtopus":clogtopus, "LaundryYeti":laundry_yeti,
    "SteamGenie":steam_genie, "BathBombBehemoth":bath_bomb_behemoth,
}
